name: Basic Checkout Lab With Exercises

on:
  push:
    branches:
      - main

jobs:
  basic-checkout:
    runs-on: ubuntu-latest
    env:
      CUSTOM_MESSAGE: "Hello from Github Actions!"
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List files
        run: ls -la

      - name: Show system info
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Operating System: $(uname -a)"
          echo "Current Directory $(pwd)"

      - name: Show additional system metrics
        run: |
          echo "Current date and time: $(date)"
          echo "Available disk space"
          df -h
          echo "Memory usage:"
          free -m
      
      - name: Display custom message
        run: echo "$CUSTOM_MESSAGE"
      
      - name: Conditional step (push-only)
        if: github.event_name == 'push'
        run: echo "This was triggered by a push event"